### ISSUE TITLE
Issue installing pyMAGEMincalc

### ISSUE THREAD

**Issue by liamjkelly** [gleesonm1/PetThermoTools#8]
Hello,

I was going through the installation for PetThermoTools and noticed in the [readthedocs](https://petthermotools.readthedocs.io/en/latest/installation.html) that there is a broken link referenced in the **Using MAGEMin** subheading. 
The command
`pip install "https://github.com/gleesonm1/pyMAGEMINcalc/refs/tags/v0.0.7.zip"` gives a 404 error, but I was able to successfully install using the command
`pip install "https://github.com/gleesonm1/pyMAGEMINcalc/archive/refs/tags/v0.0.7.zip"`

I wanted to point it out in case it was causing anybody else problems!

**Comment by gleesonm1** [comment]
Thanks for pointing this out. I've corrected that error in the documentation, it should now read correctly.
